# UFO RPC Code generator config file
# Star the repo at https://github.com/uforg/uforpc
# Read more about this file at https://uforpc.uforg.dev/r/configfile

version = 1

schema = "{{schema_path}}"

# Uncomment your desired output language(s) below and then
# run `urpc generate` to execute the code generator.

## Defines OpenAPI metadata used by other generators (e.g., playground).
## Uncomment 'output_file' to also generate a standalone spec file.
# [openapi]
# output_file = "./ufogen/openapi/openapi.yaml" # can be .json, .yaml or .yml
# title = "UFO RPC API"
# description = "UFO RPC API"
# version = "1.0.0"
# base_url = "http://example.com/api/v1/urpc"
# contact_name = "Example"
# contact_email = "api-support@example.com"
# license_name = "Proprietary"

# [playground]
# output_dir = "./ufogen/playground"
# default_base_url = "http://example.com/api/v1/urpc"
# default_headers = [
#   { key = "X-Foo", value = "bar" },
#   { key = "X-Baz", value = "qux" },
# ]

# [golang-server]
# output_file = "./ufogen/golang-server/server.go"
# package_name = "uforpc"

# [golang-client]
# output_file = "./ufogen/golang-client/client.go"
# package_name = "uforpc"

# [typescript-client]
# output_file = "./ufogen/typescript-client/client.ts"

# [dart-client]
# output_dir = "./ufogen/dart-client"
# package_name = "uforpc"
