# VDL Code generator config file
# Star the repo at https://github.com/varavelio/vdl
# Read more about this file at https://vdl.varavel.com/config

version = 1

schema = "{{schema_path}}"

# Uncomment your desired output language(s) below and then
# run `vdl generate` to execute the code generator.

## Defines OpenAPI metadata used by other generators (e.g., playground).
## Uncomment 'output_file' to also generate a standalone spec file.
# [openapi]
# output_file = "./vdlgen/openapi/openapi.yaml" # can be .json, .yaml or .yml
# title = "VDL API"
# description = "VDL API"
# version = "1.0.0"
# base_url = "http://example.com/api/v1/vdl"
# contact_name = "Example"
# contact_email = "api-support@example.com"
# license_name = "Proprietary"

# [playground]
# output_dir = "./vdlgen/playground"
# default_base_url = "http://example.com/api/v1/vdl"
# default_headers = [
#   { key = "X-Foo", value = "bar" },
#   { key = "X-Baz", value = "qux" },
# ]

# [golang-server]
# output_file = "./vdlgen/golang-server/server.go"
# package_name = "vdl"

# [golang-client]
# output_file = "./vdlgen/golang-client/client.go"
# package_name = "vdl"

# [typescript-client]
# output_file = "./vdlgen/typescript-client/client.ts"

# [dart-client]
# output_dir = "./vdlgen/dart-client"
# package_name = "vdl"
