name: Release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    name: Build and upload release
    runs-on: ubuntu-latest
    if: "!contains(github.event.release.tag_name, 'vscode')"
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create mount directories
        run: |
          mkdir -p ~/.claude ~/.config/opencode ~/.local/share/opencode

      - name: Run tests, lint and build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: /bin/bash -c "task release"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/*.tar.gz
            ./dist/*.zip
            ./dist/*.txt
