name: Release Build and Upload

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    name: Build and Upload to Release
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH directory
        run: mkdir -p /home/runner/.ssh

      - name: Run tests, lint and build
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: >
            /bin/bash -c "
              task deps &&
              task setversion &&
              task fmt-check &&
              task lint &&
              task test &&
              task build
            "

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./toolchain/dist/vdl-darwin-amd64
            ./toolchain/dist/vdl-darwin-arm64
            ./toolchain/dist/vdl-linux-amd64
            ./toolchain/dist/vdl-linux-arm64
            ./toolchain/dist/vdl-windows-amd64.exe
            ./toolchain/dist/vdl-windows-arm64.exe
            ./toolchain/dist/vdl.wasm
            ./toolchain/dist/wasm_exec.js
